Expose setAuthenticator method of HttpURLConnection for Java 9+
eclipse-ee4j/metro-jax-ws pull request #166
Opened 2020-09-18 23:32 UTC by nbosecker

Author: Nancy Bosecker <nbosecker@gmail.com>
Date: Fri Sept 18 16:24:00 2020

For Java 9+, allow clients to set an authenticator on HttpURLConnection class, which allows clients to avoid use of the default Authenticator whose cache is hidden and cannot be cleared. See https://bugs.openjdk.java.net/browse/JDK-8169495

Signed-off-by: Nancy Bosecker <nbosecker@gmail.com>

2020-09-18 23:34 UTC, nbosecker commented
Started from scratch, still getting the failure even though I add the info to the commit message.

2020-09-19 08:01 UTC, hussainnm commented
For ECA check to pass the git committer email and Signed-off-by should match the email ID registered with Eclipse. Your committer email is currently set to your company email id. Use `git log` to verify this information.

To fix the current PR follow the below steps:
```
git commit --amend --author="Nancy Bosecker <nbosecker@gmail.com>" --no-edit
git push --force-with-lease
```
This will amend the commit with the correct email id and push the changes to your fork.

2020-09-21 16:40 UTC, nbosecker commented
Done! Thanks for your help.

2020-09-21 22:31 UTC, nbosecker commented
Doesn't seem like this failure is related to my changes - how can I re-run?

2020-09-22 04:08 UTC, hussainnm requested changes
Change the imports to use jakarta instead of javax.xml.bind.* and javax.xml.ws.*.

2020-09-22 08:00 UTC, lukasj reviewed
Generally, the idea is good. Adding javadoc to newly introduced field/property would make it even better.

What I do not like that much is the maintenance burden this introduces - I do not want to repeat myself, so take a look at [details in related project](https://github.com/eclipse-ee4j/jaxb-ri/pull/1465#pullrequestreview-461481076), please.
Thanks!

2020-09-28 18:42 UTC, nbosecker commented
Thanks for the feedback. Updated by using a utility class with static method, no-op for JDK 8 and set code for JDK9+.

2020-10-05 15:46 UTC, nbosecker commented
Any feedback on this?

2020-10-05 22:11 UTC, lukasj commented on jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/developer/JAXWSProperties.java
> +	 * @since 2.4.0
should be 2.3.4 (or 3.0.0)

2020-10-05 22:14 UTC, lukasj reviewed
Yes, this is nice! just follow the code-formatting rules (having `{`, `}` on an empty line looks more like a `c` code) and I'll merge this...

2020-10-13 18:36 UTC, nbosecker commented
Updated the formatting and the version number, thanks for your help.

2020-10-14 13:36 UTC, lukasj approved these changes
LGTM

2020-10-14 13:37 UTC, merged