Bugno34600318
eclipse-ee4j/metro-jax-ws pull request #630
Opened 2022-10-04 12:13 UTC by vavishal

The faultstring in the SOAPFault contains the exception message if any which is the default current behavior

The customer has a requirement where they do not want any exception messages to be displayed in the faultstring for security concerns of exposing class

Therefore, we are adding a new system property -Dcom.sun.xml.ws.fault.doNotPrintExpMsg=true
to implement the behavior requested by the customer

Added testcase at 
./jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/fault/SOAPFaultBuilderTest.java

2022-10-04 12:33 UTC, lukasj requested changes
the property needs to follow the pattern used on other places, so it should be sth like `fqClassName.propertyName` - I'd suggest ie `com.sun.xml.ws.fault.SOAPFaultBuilder.captureExceptionMessage`

the initialization of the property value should follow the pattern used by the `captureStackTrace` field (should probably be private)

the newly added property also has to be documented:
* add a note to the `jaxws-ri/docs/release-documentation/src/main/docbook/changelog.xml`
* check `jaxws-ri/docs/release-documentation/src/main/docbook/jax-ws-ri-extensions.xml` to see if it makes sense to document the property there as well

2022-10-06 07:36 UTC, vavishal commented
I have tried to create the private variable as follows in SOAPFaultBuilder.java

private static final boolean captureExceptionMessage = getBooleanSystemProperty();

   private static boolean getBooleanSystemProperty() {
        final String propertyString = System.getProperty("com.sun.xml.ws.fault.SOAPFaultBuilder.captureExceptionMessage");
        if (propertyString == null) {
            //default value 
            return true;
        } else {
            return Boolean.getBoolean(propertyString);
        }
    }

But the above change is causing the testcase at SOAPFaultBuilderTest.java to fail always since while executing the ExceptionBeanTest.java it calls the SOAPFaultBuilder which initialized the property captureExceptionMessage with default value and also its value is not getting changed in SOAPFaultBuilderTest.java as captureExceptionMessage is a static variable

2022-10-06 07:50 UTC, lukasj commented
would non-final field with package private/public access help or having public getter/setter for the field to toggle the value help the test?

2022-10-06 09:53 UTC, vavishal commented
The following piece of code and then calling SOAPFaultBuilder.setCaptureExceptionMessage(); from the testcase helped

private static boolean captureExceptionMessage = getBooleanSystemProperty();

   private static boolean getBooleanSystemProperty() {
        final String propertyString = System.getProperty("com.sun.xml.ws.fault.SOAPFaultBuilder.captureExceptionMessage");
        if (propertyString == null) {
            default value 
            return true;
        } else {
            return Boolean.getBoolean(propertyString);
        }
    }
   public static boolean getCaptureExceptionMessage() {
        return captureExceptionMessage;
   }
   public static void setCaptureExceptionMessage() {
        captureExceptionMessage = getBooleanSystemProperty();
   }

2022-10-12 09:39 UTC, vavishal commented
Gentle reminder to review this change

2022-10-18 06:12 UTC, lukasj commented on jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/fault/SOAPFaultBuilder.java
> +   public static void setCaptureExceptionMessage() {
setter needs an argument, so one can call it and change the value from a test (for example); take a look at the `dump` and similar fields in [HttpAdapter](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/transport/http/HttpAdapter.java#L1086-L1135), the way they are being initialized and set and follow that pattern. Also note that if the method is to return boolean value, then its name should not start with `get` but rather with `is`, `should` or something implying yes/no answer

2022-10-18 07:50 UTC, lukasj commented on jaxws-ri/runtime/rt/src/test/java/com/sun/xml/ws/fault/SOAPFaultBuilderTest.java
> +            SOAPFaultBuilder.setCaptureExceptionMessage(false);
one may want to reset the value in finally after the test

2022-10-18 07:58 UTC, lukasj approved these changes
LGTM, thanks!

2022-10-18 08:25 UTC, merged